server:
  port: 8081

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://192.168.3.7:3307/imooc-red-book-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 147998
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  redis:
    host: 47.113.185.142
    port: 6379
    database: 0
    password: 147998

  data:
    mongodb:
      uri: mongodb://root:147998@47.113.185.142:27017
      database: fake-tik-tok

minio:
  endpoint: http://47.113.185.142:9000
  fileHost: http://47.113.185.142:9000
  bucketName: faketik
  accessKey: huyiqiu
  secretKey: Hyq147998
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m